### PR TITLE
Increment versions to ensure signing with a more recent certificate

### PR DESCRIPTION
**Pull request by merks**
Update the target platform to use more recently designed version.

https://github.com/eclipse/ecf/issues/17

### CODE REVIEW

**Comment by merks** [comment]
@scottslewis  I went again with the sweeping version changes because it's just too tedious to expect you to do it.   The Tycho build does work for me locally with these changes....

**Comment by scottslewis** [comment]
I've merged...thanks for the pr.   I will probably be able to produce a final build of ECF 3.14.35 with these version updates by Friday 11/19 evening ET.   I don't think I'll be able to do any testing/build shape checking before then.

**Comment by scottslewis** [comment]
I've done this merge and produced a build here:

https://download.eclipse.org/rt/ecf/snapshot/site.p2/3.14.35.v20221117-1507/

Is it possible to run the checker on this new repo to make sure that the signing + version updates + target update worked correctly?   Thanksinadvance.

**Comment by merks** [comment]
Looks very good, but I missed I missed one:

image

I'll create a PR for that...

BTW, I think these are all still the exact same bundles you used before, just rebuilt/resigned and therefore a new qualifier.

**Comment by scottslewis** [comment]
Merged and produced new build here:

https://download.eclipse.org/rt/ecf/snapshot/site.p2/3.14.36.v20221118-2058/

**Pull request merged**
