### PR TITLE
remove blank Javadoc

### PR DESCRIPTION
**Pull request by jukzi**
Removes ecj warning
"Javadoc: Description expected after this reference"

### CODE REVIEW

**Comment by scottslewis** [comment]
First, thanks for removing these javadoc warnings.   

To merge these changes and build/release, however, I have to manually update each bundle version in both the manifest.mf and the pom.xml for each effected project (i.e. every project that has a changed source file in it).   For most changes I do this myself. but right now I'm not able to spend the time on it...to only remove javadocs warnings. 

So, if you are able to add in the necessary version updates of the effected projects to the pull request (both bundle and feature project versions) then I will merge this pull request.   If you are not able at the moment, then it will  probably have to wait for a month or so.

**Comment by jukzi** [comment]
I could do the version updates if the build would raise an error about missing updates. It does not even run tests and missing version updates are only logged as warning.
Anyway this commit has plenty of time. I only try to get rid of warnings in platform workspace.


Currently the build complains about many more version updates missing then i touched in this commit:
```
Only qualifier changed for (org.eclipse.ecf.identity/3.10.0.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (3.10.0.v20230422-0242)
Only qualifier changed for (org.eclipse.ecf/3.11.0.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (3.11.0.v20230507-1923)
Only qualifier changed for (org.eclipse.ecf.remoteservice.asyncproxy/2.1.200.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (2.1.200.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.remoteservice/8.14.0.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (8.14.0.v20230528-2254)
Only qualifier changed for (ch.ethz.iks.slp/1.4.1.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.4.1.v20230528-2254)
Only qualifier changed for (org.eclipse.osgi.services.remoteserviceadmin/1.6.301.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.6.301.v20221117-1507)
Only qualifier changed for (org.eclipse.ecf.osgi.services.remoteserviceadmin.proxy/1.0.102.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.102.v20221117-1507)
Only qualifier changed for (org.eclipse.ecf.osgi.services.remoteserviceadmin/4.9.3.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (4.9.3.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.osgi.services.remoteserviceadmin.console/1.3.1.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.3.1.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.sharedobject/2.6.200.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (2.6.200.v20210922-0753)
Only qualifier changed for (org.eclipse.ecf.provider.r_osgi/3.7.0.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (3.7.0.v20210919-0222)
Only qualifier changed for (org.eclipse.ecf.remoteservice.eventadmin/1.3.101.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.3.101.v20221117-1507)
Only qualifier changed for (org.eclipse.ecf.provider.filetransfer/3.3.0.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (3.3.0.v20230422-0242)
Only qualifier changed for (org.eclipse.ecf.provider.filetransfer.httpclient45/1.0.600.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.600.v20220215-0126)
Only qualifier changed for (org.eclipse.ecf.provider.zookeeper/1.2.500.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.2.500.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.provider.jslp/3.2.302.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (3.2.302.v20221117-1507)
Only qualifier changed for (org.eclipse.ecf.provider.remoteservice/4.6.1.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (4.6.1.v20210926-0332)
Only qualifier changed for (org.eclipse.ecf.remoteservice.servlet/1.0.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.201.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.provider.filetransfer.httpclient4/1.1.502.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.1.502.v20221117-1507)
Only qualifier changed for (org.eclipse.ecf.provider.dnssd/1.2.302.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.2.302.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.provider.filetransfer.httpclient5/1.1.0.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.1.0.v20230423-0417)
Only qualifier changed for (com.mycorp.examples.timeservice/1.1.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.1.201.v20221117-1507)
Only qualifier changed for (com.mycorp.examples.timeservice.async/2.1.101.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (2.1.101.v20221117-1507)
Only qualifier changed for (com.mycorp.examples.timeservice.consumer/1.1.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.1.201.v20221117-1507)
Only qualifier changed for (com.mycorp.examples.timeservice.consumer.ds/1.0.401.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.401.v20221117-1507)
Only qualifier changed for (com.mycorp.examples.timeservice.consumer.ds.async/1.0.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.201.v20221117-1507)
Only qualifier changed for (com.mycorp.examples.timeservice.host/1.1.400.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.1.400.v20210403-2253)
Only qualifier changed for (org.eclipse.ecf.presence/2.1.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (2.1.201.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.provider.xmpp/3.2.402.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (3.2.402.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.ui/2.3.0.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (2.3.0.v20230422-0143)
Only qualifier changed for (org.eclipse.ecf.presence.ui/2.4.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (2.4.201.v20221117-1507)
Only qualifier changed for (org.eclipse.ecf.example.clients/2.0.300.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (2.0.300.v20211031-0234)
Only qualifier changed for (org.eclipse.ecf.datashare/3.0.301.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (3.0.301.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.discovery.ui.model/3.0.202.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (3.0.202.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.discovery.ui.edit/3.0.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (3.0.201.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.discovery.ui/3.0.301.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (3.0.301.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.discovery.ui.browser/1.0.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.201.v20221117-1507)
Only qualifier changed for (org.eclipse.ecf.discovery.ui.properties/3.0.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (3.0.201.v20221117-1507)
Only qualifier changed for (org.eclipse.ecf.discovery.ui.properties.tabbed/3.0.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (3.0.201.v20221117-1507)
Only qualifier changed for (org.eclipse.ecf.discovery.ui.userinput/1.0.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.201.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.sync/2.0.302.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (2.0.302.v20221117-1507)
Only qualifier changed for (org.eclipse.ecf.docshare/3.0.401.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (3.0.401.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.filetransfer.ui/1.5.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.5.201.v20221117-1507)
Only qualifier changed for (org.eclipse.ecf.presence.bot/1.3.301.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.3.301.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.remoteservice.ui/3.4.400.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (3.4.400.v20210403-2254)
Only qualifier changed for (org.eclipse.ecf.ssl/1.3.0.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.3.0.v20230507-1921)
Only qualifier changed for (org.eclipse.ecf.ui.capabilities/1.0.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.201.v20221117-1507)
Only qualifier changed for (org.eclipse.team.ecf.core/1.0.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.201.v20230528-2254)
Only qualifier changed for (org.eclipse.team.ecf.ui/1.0.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.201.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.protocol.msn/1.2.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.2.201.v20221117-1507)
Only qualifier changed for (org.eclipse.ecf.provider.bittorrent/0.3.401.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (0.3.401.v20221117-1507)
Only qualifier changed for (org.eclipse.ecf.provider.datashare/1.6.1.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.6.1.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.provider.datashare.nio/0.9.301.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (0.9.301.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.provider.filetransfer.efs/1.5.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.5.201.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.provider.filetransfer.httpclient45.win32/1.0.500.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.500.v20211031-0225)
Only qualifier changed for (org.eclipse.ecf.provider.filetransfer.httpclient4.ssl/1.1.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.1.201.v20221117-1507)
Only qualifier changed for (org.eclipse.ecf.provider.filetransfer.httpclient5.win32/1.1.0.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.1.0.v20230423-0417)
Only qualifier changed for (org.eclipse.ecf.provider.filetransfer.scp/2.1.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (2.1.201.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.provider.filetransfer.ssl/1.1.0.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.1.0.v20230422-0242)
Only qualifier changed for (org.eclipse.ecf.provider.irc/1.3.401.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.3.401.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.provider.msn/1.2.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.2.201.v20221117-1507)
Only qualifier changed for (org.eclipse.ecf.provider.xmpp.datashare/1.0.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.201.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.provider.xmpp.remoteservice/1.2.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.2.201.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.provider.xmpp.ui/2.2.301.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (2.2.301.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.server/2.1.301.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (2.1.301.v20221117-1507)
Only qualifier changed for (org.eclipse.ecf.discovery.feature.feature.jar/1.0.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.201.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.discovery.slp.feature.feature.jar/1.0.102.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.102.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.discovery.zookeeper.feature.feature.jar/1.0.400.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.400.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.core.ssl.feature.feature.jar/1.1.501.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.1.501.v20230507-1921)
Only qualifier changed for (org.eclipse.ecf.datashare.feature.feature.jar/1.0.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.201.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.discovery.dnssd.feature.feature.jar/1.0.102.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.102.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.docshare.feature.feature.jar/1.0.201.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.0.201.v20230528-2254)
Only qualifier changed for (org.eclipse.ecf.filetransfer.httpclient4.feature.feature.jar/3.14.32.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (3.14.32.v20221207-1049)
Only qualifier changed for (org.eclipse.ecf.filetransfer.httpclient45.feature.feature.jar/1.1.100.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.1.100.v20221207-1049)
Only qualifier changed for (org.eclipse.ecf.filetransfer.httpclient4.ssl.feature.feature.jar/1.1.301.v20231107-1350). Expected to have bigger x.y.z than what is available in baseline (1.1.301.v20221117-1507)
```

**Comment by scottslewis** [comment]
Ok.   Then this will wait.

**Comment by jukzi** [comment]
@scottslewis i added version bump to my best knowledge, but the build fails with
```
Cannot resolve project dependencies:
 Software being installed: org.eclipse.ecf.server.generic.feature.feature.group 1.2.200.qualifier
 Missing requirement: org.eclipse.ecf.remoteservice.feature.feature.group 2.6.1.qualifier requires 'org.eclipse.equinox.p2.iu; org.eclipse.ecf.remoteservice.asyncproxy [2.1.200,2.1.201)' but it could not be found
 Cannot satisfy dependency: org.eclipse.ecf.provider.generic.remoteservice.feature.feature.group 1.2.1.qualifier depends on: org.eclipse.equinox.p2.iu; org.eclipse.ecf.remoteservice.feature.feature.group [2.1.0,3.0.0)
 Cannot satisfy dependency: org.eclipse.ecf.server.generic.feature.feature.group 1.2.200.qualifier depends on: org.eclipse.equinox.p2.iu; org.eclipse.ecf.provider.generic.remoteservice.feature.feature.group [1.0.0,2.0.0)

```
I don't understand the message. any idea how to solve this?

**Comment by jukzi** [comment]
Closing as it seems to be no interest in this change.

**Pull request closed without merging**
