### PR TITLE
Add SSLContext Default

### PR DESCRIPTION
**Pull request by JavaJoeS**
No effect unless an org.eclipse.core.pki package is installed and configured.

### CODE REVIEW

**Comment by JavaJoeS** [comment]
@eclipse-ecf-bot Can I get a review?

**Comment by scottslewis** [comment]
Hi @JavaJoeS 

I've merged your changes and added a pr 107 for some necessary meta-data updates (version increment for bundle and features along with maven deploy stuff).

The snapshot p2 repo will be produced here:  https://download.eclipse.org/rt/ecf/snapshot/site.p2/ for your testing.

The thing to look for in the most recent repo, is that this feature:   org.eclipse.ecf.core.ssl.feature will have (new) version 1.1.600.

**Comment by scottslewis** [comment]
Hi @JavaJoeS 

I would like to produce a release of ECF (for subsequent contribution to Eclipse/p2) version 3.15.0.   Before doing so, however, I would like to request that you test/verify that the changes for this pr in build available here

https://download.eclipse.org/rt/ecf/snapshot/site.p2/

have not resulted in any regression for use of https with or without your pki work. Would you please be able to verify that there are no regressions in both cases (with or without pki) in the new build as soon as is reasonable?   I would like to build and release ECF 3.15.0 before 5/13/24 if at all possible, and this testing is the main blocker for release at this point.

**Comment by JavaJoeS** [comment]
@scottslewis  testing went well, its a go!

**Comment by scottslewis** [comment]
Hi @JavaJoeS.   Thanks.   Unfortunately, I can't simply release 3.15.0.  As per Eclipse rules, I scheduled a progress review:

https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/743

It's going to be at least the week of 5/20 before I can release 3.15.0.   @JavaJoeS will you please notify the platform people?  I believe your one change to org.eclipse.ecf.ssl is the only change to the ECF filetransfer code in this release.   I'm assuming that everything should be targeting the 2024-06 Eclipse release, which I believe is coming up fast but don't have the release schedule in my head at the moment.

**Pull request merged**
